### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by dreamer14jon** [dzakyputra/sentweetbot#1]
I am using https://repl.it and i have been getting this error message. wondering if you will be able to help.

 python3 main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from google.cloud import language
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/google/cloud/language.py", line 17, in <module>
    from google.cloud.language_v1 import LanguageServiceClient
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/google/cloud/language_v1/__init__.py", line 17, in 
<module>
    from google.cloud.language_v1 import types
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/google/cloud/language_v1/types.py", line 18, in <mo
dule>
    from google.api import http_pb2
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/google/api/http_pb2.py", line 35, in <module>
    _descriptor.FieldDescriptor(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/google/protobuf/descriptor.py", line 530, in __new_
_
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.
exit status 1

**Comment by dzakyputra** [comment]
Hi, I have never tried running it on repl, but can you can try change this lines

```
from google.cloud import language
from google.cloud.language import enums
from google.cloud.language import types
```

into this

`import google`

then you can change the code where `language`, `enums`, and `types` appear into `google.cloud.language`, `google.cloud.language.enums`, `google.cloud.language.types` respectively.

I don't know if this solves the problem, but you can try it first.

**Comment by dreamer14jon** [comment]
import tweepy
import re



from telegram.ext import Updater, MessageHandler, Filters
import google.cloud.language
import google.cloud.language.enums
import google.cloud.language.types
from datetime import datetime, timedelta
from nltk.tokenize import WordPunctTokenizer

would this be correct?

Still error :(

 python3 main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import google.cloud.language
ModuleNotFoundError: No module named 'google.cloud'
exit status 1

**Comment by dreamer14jon** [comment]
just wondering if there is a online tool i can use? i am a teacher and i am using this as a class example of understanding data

**Comment by dzakyputra** [comment]
You might want to try Google Colab --> https://colab.research.google.com/

**Comment by dreamer14jon** [comment]
![image](https://user-images.githubusercontent.com/64797433/81050076-fceeea80-8ef1-11ea-963a-ae4fb8b4126f.png)
 is this normal?

**Comment by dzakyputra** [comment]
> ![image](https://user-images.githubusercontent.com/64797433/81050076-fceeea80-8ef1-11ea-963a-ae4fb8b4126f.png)
> is this normal?

yes it indicates the script is running

**Comment by dreamer14jon** [comment]
I have found out the issue.

from google.colab import drive
drive.mount('/content/gdrive')

#ensure the file is accessible
!ls /content/gdrive/'My Drive'/'Colab Notebooks'/temp

import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/content/gdrive/My Drive/Colab Notebooks/temp/creds.json"

#ensure the path is set correctly
!echo $GOOGLE_APPLICATION_CREDENTIALS

**Comment by dreamer14jon** [comment]
last question :) how do i pull out to include the number of tweets it searched through?

**Comment by dreamer14jon** [comment]
https://web.telegram.org/#/im?p=@JonSentimentTwitter_bot

This is the bot i have created with the help of your code :)

**Comment by dzakyputra** [comment]
> last question :) how do i pull out to include the number of tweets it searched through?

You actually set the number of tweets from this line
    
```final_score = analyze_tweets(keyword, 50)```

**Comment by dzakyputra** [comment]
> I have found out the issue.
> 
> from google.colab import drive
> drive.mount('/content/gdrive')
> 
> #ensure the file is accessible
> !ls /content/gdrive/'My Drive'/'Colab Notebooks'/temp
> 
> import os
> os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/content/gdrive/My Drive/Colab Notebooks/temp/creds.json"
> 
> #ensure the path is set correctly
> !echo $GOOGLE_APPLICATION_CREDENTIALS

I am happy that you can resolve this issue by yourself, great!

**Comment by kingyash1** [comment]
> I have found out the issue.
> 
> from google.colab import drive
> drive.mount('/content/gdrive')
> 
> #ensure the file is accessible
> !ls /content/gdrive/'My Drive'/'Colab Notebooks'/temp
> 
> import os
> os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="/content/gdrive/My Drive/Colab Notebooks/temp/creds.json"
> 
> #ensure the path is set correctly
> !echo $GOOGLE_APPLICATION_CREDENTIALS

how you solved the error can you help me too?
